#!/bin/bash

export TERM='xterm-256color'

declare -a files=(
  $HOME/.bash_exports
  $HOME/.bash_functions
  $HOME/.bash_prompt
  $HOME/.bash_paths
  $HOME/.bash_profile.local
  $HOME/.git_completion.sh
)

for index in ${!files[*]}
do
  if [[ -r ${files[$index]} ]]; then
    source ${files[$index]}
  fi
done

unset files

if [[ "$unamestr" == 'Linux' ]]; then
    eval `dircolors ${HOME}/.dir_colors`
fi

eval "$(rbenv init -)"
eval "$(pyenv init -)"

export GPG_TTY=$(tty)

