" .vimrc

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#rc()

Plugin 'VundleVim/Vundle.vim'

Plugin 'mileszs/ack.vim'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'fatih/vim-go'

call vundle#end()
filetype plugin indent on

if has("syntax")
    " Enable syntax highlighting
    syntax enable
    " Set 256 color terminal support
    set t_Co=256
    " Set light background
    set background=light
endif

let mapleader=","

set backspace=indent,eol,start
set ttyfast
set encoding=utf-8 nobomb

set nowrap
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set number
set nostartofline
set columns=120

set showmatch
set hlsearch

set backupdir=$HOME/.vim/backups
set directory=$HOME/.vim/swaps

set viminfo+=n$HOME/.vim/.viminfo

cmap w!! w !sudo tee % >/dev/null

" key bindings
map <C-n> :NERDTreeToggle<CR>

